### ISSUE TITLE
Allow to know if the current user has a password set

### ISSUE THREAD

**Issue by spaenleh** [graasp/graasp#1256]
We would like to know if the current user has a password so we can use the right route (POST or PATCH) in account.

Not sure if this requires a new endpoint or if we will simply add a new prop to the currentMember response.

**Comment by Defferrard** [comment]
Since the currentMember is called multiple time when using the application, and the password is an sensitive information (in my opinion). Moreover it would join a table which is not necessary for most of the use cases, that's why I prefer to create a new endpoint. I don't know what is the opinion of everyone.

I don't have a good name for the endpoint. Here some propositions
- **GET /members/current/password** : Can be confusing
- **GET /members/current/has-password** : Not fan of the "has"
- **GET /members/current/password/status**

**Comment by spaenleh** [comment]
@Defferrard Makes sens. I like `GET /members/current/password/status`
