### ISSUE TITLE
import copied item results in weird download file

### ISSUE THREAD

**Issue by pyphilia** [graasp/graasp#1269]
`Screenshot 2024-07-05 at 13.45.54.png (2)`
gets downloaded as
`Screenshot%202024-07-05%20at%2013.45.54.png%20(2)`

**Comment by Defferrard** [comment]
I think this issue is related to every item we want to download, and I believe it should not be fixed.

We're using `encodeURIComponent(...)` multiple times in `src/services/item/plugins/importExport/index.ts` and it is useful to encode some dangerous character when downloading any item. It could lead to some injection in the `Content-Disposition`

**Comment by Defferrard** [comment]
We should use an adapted encoding.
