### ISSUE TITLE
Use read replicas

### ISSUE THREAD

**Issue by pyphilia** [graasp/graasp#286]
https://github.com/gajus/slonik#routing-queries-to-different-connections

**Comment by dialexo** [comment]
Deployment is failing at https://github.com/graasp/graasp/actions/runs/3787978449.

Output from the AWS ECS service logs:

```
29/12/2022, 11:18:15 /home/node/app/dist/plugins/database.js:59	graasp-development
29/12/2022, 11:18:15 Object.assign(options.interceptors, [...options.interceptors, readOnlyInterceptor]);	graasp-development
29/12/2022, 11:18:15 ^	graasp-development
29/12/2022, 11:18:15 TypeError: options.interceptors is not iterable	graasp-development
29/12/2022, 11:18:15 at /home/node/app/dist/plugins/database.js:59:57	graasp-development
29/12/2022, 11:18:15 at Generator.next (<anonymous>)	graasp-development
29/12/2022, 11:18:15 at /home/node/app/dist/plugins/database.js:8:71	graasp-development
29/12/2022, 11:18:15 at new Promise (<anonymous>)	graasp-development
29/12/2022, 11:18:15 at __awaiter (/home/node/app/dist/plugins/database.js:4:12)	graasp-development
29/12/2022, 11:18:15 at plugin (/home/node/app/dist/plugins/database.js:14:61)	graasp-development
29/12/2022, 11:18:15 at Plugin.exec (/home/node/app/node_modules/avvio/plugin.js:132:19)	graasp-development
29/12/2022, 11:18:15 at Boot.loadPlugin (/home/node/app/node_modules/avvio/plugin.js:274:10)	graasp-development
29/12/2022, 11:18:15 at processTicksAndRejections (node:internal/process/task_queues:83:21)	graasp-development
```

**Comment by dialexo** [comment]
:warning: we need to check if the read replica is actually used! Since (almost) all our DB operations are wrapped in transactions, verify if:
- read replicas are used
- only read operations are performed on the read replicas
- the transactions are still consistent (i.e. either reads and writes of a single transaction are always performed on the same instance, or there needs to be some mechanism to ensure that switching between replicas for reads and writes does not affect consistency!)

**Comment by dialexo** [comment]
Given our current measurements, all slonik transactions use the main database instance (and not the read replica). We'll need to check with #282 if TypeORM can automatically direct read queries to the replicas (see https://orkhan.gitbook.io/typeorm/docs/multiple-data-sources#replication)
