### ISSUE TITLE
don't create member immediately on register

### ISSUE THREAD

**Issue by pyphilia** [graasp/graasp#994]
handle pending members that actually click on auth for the first time to create the member.
So we can delete pending members that never logged in.

**Comment by Defferrard** [comment]
This issue is on hold until #1026 is solved.

The discussed strategy is :
- Add a `LastConnection` column to table member.
- Add a `ValidatedMember` view to filter member that have already been connected.
- The `LastConnection` value will be updated when a user click on his `MagicLink` or connect with his password.

On long term, we've discussed that we could :
- Create a `Log` table
- Log every connection, so we could know who are the `DailyConnectedUser`
- The problem is that we're going to duplicate the `LastConnection` data.
   - Do we still need this information on Member table ?
   - If not, is joining table too slow ? Which columns needs to be indexed ?
